---


- name: Provide irods_etc_hosts definitions
  vars:
    # yamllint disable-line rule:line-length
    all_hosts: "{{ ([irods_db_host] + irods_hosts) | reject('eq', 'localhost') | unique | list }}"
  ansible.builtin.set_fact:
    irods_etc_hosts: >-
      {{ irods_etc_hosts | default([]) +
      [ {'hostname' : item,
         'ip' : hostvars[item].irods_ip if 'irods_ip' in hostvars[item] else
                hostvars[item].ansible_default_ipv4.address,
         'fqdn' : hostvars[item].inventory_hostname},
      ] }}
  loop: "{{ all_hosts }}"

- name: Put irods_etc_hosts into /etc/hosts
  ansible.builtin.lineinfile:
    path: "/etc/hosts"
    unsafe_writes: true  # avoid problems with systemd/docker mounted file
    line: "{{ item.ip }} {{ item.fqdn }} {{ item.hostname }}"
  loop: "{{ irods_etc_hosts }}"
