---

# init iRODS distribution for non-IES

- name: Check if we need to initialize iRODS distribution
  ansible.builtin.command: "test -f /var/lib/irods/VERSION.json"
  register: irods_initialized
  failed_when: false
  changed_when: irods_initialized.rc != 0

# mimic setup_irods.py except for creating default resources with fixed path
- name: Initialize iRODS distribution for non-IES (resource only server)
  ansible.builtin.command:
    "cp /var/lib/irods/VERSION.json.dist /var/lib/irods/VERSION.json"
  when:
    - irods_initialized.rc != 0

- name: Configure iRODS server
  ansible.builtin.include_tasks: irods.yml
