---
image: quay.io/ansible/toolset:3.5.0

stages:
  - test-centos
  - test-ubuntu

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip"
  GIT_STRATEGY: clone

cache:
  paths:
    - .pip/

before_script:
  - python3 -V
  - pip3 install ansible molecule docker
  - ansible --version
  - molecule --version
  - docker --version

role irods (CentOS 7):
  stage: test-centos
  script:
    - cd roles/irods
    - MOLECULE_DISTRO=centos7 molecule test --all

role irods (Ubuntu 18.04):
  stage: test-ubuntu
  script:
    - cd roles/irods
    - MOLECULE_DISTRO=ubuntu1804 molecule test --all
