---
# prepare hosts for SSL setup with self-signed certificates

- name: create certificates directory
  file:
    path: "{{ item | dirname }}"
    state: directory
  loop:
    - "{{ irods_ssl_certificate_key_file }}"
    - "{{ irods_ssl_certificate_chain_file }}"
    - "{{ irods_ssl_ca_certificate_file }}"

- name: "Generate an OpenSSL private key with the default values (4096 bits, RSA)"
  community.crypto.openssl_privatekey:
    path: "{{ irods_ssl_certificate_key_file }}"

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: "/tmp/server.csr"
    privatekey_path: "{{ irods_ssl_certificate_key_file }}"
    common_name: "{{ inventory_hostname }}"

- name: Generate a Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: "{{ irods_ssl_certificate_chain_file }}"
    privatekey_path: "{{ irods_ssl_certificate_key_file }}"
    csr_path: "/tmp/server.csr"
    provider: selfsigned
- name: Get hosts certificates
  fetch:
    src: "{{ irods_ssl_certificate_chain_file }}"
    dest: "/tmp/{{ inventory_hostname }}.crt"
    flat: true
- name: Distribute hosts certificates
  copy:
    src: "/tmp/{{ item }}.crt"
    dest: "/tmp/{{ item }}.crt"
  loop: "{{ play_hosts }}"
- name: Gather hosts certificates into a bundle ca.crt
  assemble:
    src: "/tmp"
    regexp: "^.*\\.crt$"
    dest: "{{ irods_ssl_ca_certificate_file }}"
