---

# init iRODS distribution for non-IES

- name: Check if we need to initialize iRODS distribution
  command: "test -f /var/lib/irods/VERSION.json"
  register: irods_initialized
  failed_when: false
  changed_when: irods_initialized.rc != 0

- name: Check if we need to initialize iRODS distribution
  command: "test -f /var/lib/irods/VERSION.json"
  register: irods_initialized
  failed_when: false
  changed_when: irods_initialized.rc != 0


# mimic setup_irods.py except for creating default resources with fixed path
- name: Initialize iRODS distribution for non-IES (resource only server)
  command: "cp /var/lib/irods/VERSION.json.dist /var/lib/irods/VERSION.json"
  when:
    - irods_initialized.rc != 0

# configure iRODS server
- include_tasks: irods.yml
