---
# tasks file for ansible-role-irods

# ICAT settings
- name: Setup Catalog Database
  include_role:
    name: geerlingguy.postgresql
    apply:
      become: yes
  vars:
    postgresql_databases:
      - name: "{{ irods_db_name }}"
    postgresql_users:
      - name: "{{ irods_db_username }}"
#        db: "{{ irods_db_name }}" # chicken and eggs problem with postgresql_databases
#        priv: "ALL"
        password: "{{ irods_db_password }}"
    postgres_users_no_log: true
  when: ansible_role_irods_is_catalog

- name: Add irods user to database
  postgresql_privs:
    db: "{{ irods_db_name }}"
    roles: "{{ irods_db_username }}"
    password: "{{ irods_db_password }}"
    type: database
    privs: "ALL"
  no_log: true
  become_user: postgres
  become: true
  when: ansible_role_irods_is_catalog

# iRODS server settings
- name: Create iRODS service account
  user:
    name: "irods"
    home: "/var/lib/irods"
    comment: "iRODS Administrator"
    password: "!"

- name: setup iRODS CentOS Yum repository
  yum_repository:
    name: "renci-irods"
    description: "RENCI iRODS Repository"
    baseurl: "https://packages.irods.org/yum/pool/centos$releasever/$basearch"
    enabled: true
    gpgkey: "https://packages.irods.org/irods-signing-key.asc"
    gpgcheck: true

- name: Install iRODS server packages
  package:
    pkg:
      - irods-server
      - irods-database-plugin-postgres

- name: iRODS server setup file
  template:
    src: "templates/setup_irods.json.j2"
    dest: "/etc/irods/setup_irods.json"
    mode: 0600
    owner: irods
    group: irods

- name: Check if we need to initialize iRODS distribution
  command: "test -f /var/lib/irods/VERSION.json"
  register: irods_initialized
  failed_when: false
  changed_when: irods_initialized.rc != 0

- name: Initialize iRODS distribution
  command: "python /var/lib/irods/scripts/setup_irods.py --json_configuration_file=/etc/irods/setup_irods.json"
  when: irods_initialized.rc != 0
  notify:
    - restart irods

- name: iRODS server configuration file
  template:
    src: "templates/server_config.json.j2"
    dest: "/etc/irods/server_config.json"
    mode: 0600
    owner: irods
    group: irods
  notify:
    - restart irods

- name: iRODS service account environment directory
  file:
    path: "/var/lib/irods/.irods"
    state: directory
    mode: 0700
    owner: irods
    group: irods

- name: iRODS service account environment file
  template:
    src: "templates/service_account_irods_environment.json.j2"
    dest: "/var/lib/irods/.irods/irods_environment.json"
    mode: 0600
    owner: irods
    group: irods
  notify:
    - restart irods
