---

galaxy_info:
  author: Pierre Gay
  description: maintainer
  company: MCIA

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  license: GPL-3.0-or-later

  min_ansible_version: 2.9

  # min_ansible_container_version:

  platforms:
    - name: CentOS
      versions:
        - 7

  galaxy_tags: []

dependencies: []
