---

galaxy_info:
  author: "Pierre Gay (@pigay)"
  description: maintainer
  company: MCIA

  role_name: irods
  namespace: mcia

  license: CC-BY

  min_ansible_version: 2.9

  platforms:
    - name: CentOS
      versions:
        - 7

  galaxy_tags: []

dependencies: []
