---
# iRODS role verification

- name: Verify simple iput/iget commands
  hosts: all
  tasks:
    - name: test iput
      # yamllint disable-line rule:line-length
      command: "iput -f /var/lib/irods/VERSION.json {{ inventory_hostname }}-VERSION.json"
      register: verify_iput
      become: true
      become_user: irods
      changed_when: false
    - name: test iget
      command: "iget -f {{ inventory_hostname }}-VERSION.json /tmp/VERSION.json"
      register: verify_iget
      become: true
      become_user: irods
      changed_when: false
    - name: test iget/iput results (cmp)
      command: "cmp /var/lib/irods/VERSION.json /tmp/VERSION.json"
      register: verify_igetiput_diff
      become: true
      become_user: irods
      changed_when: false
    - name: assertions
      assert:
        that:
          - verify_iput.rc == 0
          - verify_iget.rc == 0
          - verify_igetiput_diff.rc == 0
