---
# vars file for RedHat

# yamllint disable-line rule:line-length
irods_package_extension: "{{ '' if irods_version is none else '-' + irods_version }}"
# yamllint disable-line rule:line-length
irods_server_pkgname: "irods-server{{ irods_package_extension }}"
# yamllint disable-line rule:line-length
irods_database_pkgname: "irods-database-plugin-postgres{{ irods_package_extension }}"
