---
- name: Converge
  hosts: all
  vars:
    irods_catalog_provider_hosts: ["instance"]
    irods_hosts: ["instance"]
    irods_admin_password: "VERY_SECRET_ADMIN_PASSWORD"
    irods_database_user_password_salt: "VERY_SECRET_SALT"
    irods_negotiation_key: "09876543210987654321098765432109"
    irods_db_password: "VERY_SECRET_PASSWORD"
    irods_server_control_plane_key: "12345678901234567890123456789012"
    irods_zone_key: "VERY_SECRET_KEY"
  tasks:
    - name: "include scenario common variables"
      include_vars: "vars.yml"
    - name: Update repositories cache (if older than 1 day) (debian)
      apt:
        update_cache: true
        cache_valid_time: 86400
      when: ansible_os_family == 'Debian'
    - name: "Configure host as a database server"
      include_role:
        name: irods
        tasks_from: "database-role-PostgreSQL"
    - name: "create iRODS database on server"
      include_role:
        name: irods
        tasks_from: "database-configure-PostgreSQL"
    - name: "Include irods ansible role"
      include_role:
        name: irods
